import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import SessionWrapper from "@/components/SessionWrapper";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Image from 'next/image';
import AppSidebar from "@/components/layout/AppSidebar";
import { ToastContainer } from 'react-toastify';
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faLink } from "@fortawesome/free-solid-svg-icons";
import mongoose from "mongoose";
import Page from "@/models/Page";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: `Account`,
  description: "Generated by create next app",
};

export default async function AppLayout({ children }) {
  const session = await getServerSession(authOptions);
  if (!session) {
    return redirect('/login')
  }
  mongoose.connect(process.env.MONGODB_URI);
  const page = await Page.findOne({ owner: session?.user?.email })
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionWrapper>
          <ToastContainer />
          <main className="md:flex min-h-screen transition-all">
            <aside className="bg-white shadow min-w-48 p-4 py-8">
              <div className="sticky top-0 p-2">
                <div className="rounded-full bg-black overflow-hidden w-[90px] flex h-[90px] mx-auto">
                  <Image src={session.user.image} width={90} height={90} alt={session.user.name} />
                </div>
                {page && (
                  <Link href={`/${page.uri}`} target="_blank" className="flex gap-1 mt-4 items-center justify-center">
                    <FontAwesomeIcon className="text-blue-500 text-xl" icon={faLink} />
                    <span className="text-xl text-gray-300">/</span>
                    <span className="underline">{page.uri}</span>
                  </Link>
                )}
                <AppSidebar />
              </div>
            </aside>
            <div className="grow">
              {children}
            </div>
          </main>
        </SessionWrapper>
      </body>
    </html>
  );
}
