/**
 * Centralized Theme Preset Registry
 * Provides visual design tokens for profile themes with guaranteed accessible contrast.
 */

export const themes = [
  {
    id: 'default',
    name: 'Midnight',
    description: 'Signature dark aesthetic with deep indigo gradients',
    previewColor: '#0f172a',
    previewGradient: 'from-blue-950 to-indigo-900',
    pageBg: 'bg-gradient-to-b from-blue-950 to-indigo-900',
    headerBg: '#0f172a',
    headerOverlay: 'bg-gradient-to-b from-black/20 via-transparent to-blue-950/90',
    cardBg: 'bg-white/10 hover:bg-white/20',
    cardBorder: 'border border-white/10',
    textColor: 'text-white',
    headingColor: 'text-white',
    mutedTextColor: 'text-blue-200/80',
    subtitleColor: 'text-blue-200/70',
    iconBg: 'bg-gradient-to-br from-blue-500/50 to-indigo-600/50',
    buttonStyle: 'bg-white/10 hover:bg-white/20 text-white',
  },
  {
    id: 'emerald',
    name: 'Emerald Forest',
    description: 'Lush evergreen gradients and calm teal accents',
    previewColor: '#064e3b',
    previewGradient: 'from-emerald-950 to-teal-900',
    pageBg: 'bg-gradient-to-b from-emerald-950 to-teal-900',
    headerBg: '#064e3b',
    headerOverlay: 'bg-gradient-to-b from-black/20 via-transparent to-emerald-950/90',
    cardBg: 'bg-white/10 hover:bg-white/20',
    cardBorder: 'border border-emerald-500/20',
    textColor: 'text-white',
    headingColor: 'text-white',
    mutedTextColor: 'text-emerald-200/80',
    subtitleColor: 'text-emerald-200/70',
    iconBg: 'bg-gradient-to-br from-emerald-500/50 to-teal-600/50',
    buttonStyle: 'bg-white/10 hover:bg-white/20 text-white',
  },
  {
    id: 'sunset',
    name: 'Sunset Glow',
    description: 'Warm evening hues from rich crimson to golden amber',
    previewColor: '#4c0519',
    previewGradient: 'from-rose-950 via-purple-950 to-amber-950',
    pageBg: 'bg-gradient-to-b from-rose-950 via-purple-950 to-amber-950',
    headerBg: '#4c0519',
    headerOverlay: 'bg-gradient-to-b from-black/20 via-transparent to-rose-950/90',
    cardBg: 'bg-white/10 hover:bg-white/20',
    cardBorder: 'border border-rose-500/20',
    textColor: 'text-white',
    headingColor: 'text-white',
    mutedTextColor: 'text-rose-200/80',
    subtitleColor: 'text-rose-200/70',
    iconBg: 'bg-gradient-to-br from-rose-500/50 to-amber-600/50',
    buttonStyle: 'bg-white/10 hover:bg-white/20 text-white',
  },
  {
    id: 'ocean',
    name: 'Deep Ocean',
    description: 'Cool cyan tones flowing into abyss navy',
    previewColor: '#083344',
    previewGradient: 'from-cyan-950 via-blue-950 to-slate-950',
    pageBg: 'bg-gradient-to-b from-cyan-950 via-blue-950 to-slate-950',
    headerBg: '#083344',
    headerOverlay: 'bg-gradient-to-b from-black/20 via-transparent to-cyan-950/90',
    cardBg: 'bg-white/10 hover:bg-white/20',
    cardBorder: 'border border-cyan-500/20',
    textColor: 'text-white',
    headingColor: 'text-white',
    mutedTextColor: 'text-cyan-200/80',
    subtitleColor: 'text-cyan-200/70',
    iconBg: 'bg-gradient-to-br from-cyan-500/50 to-blue-600/50',
    buttonStyle: 'bg-white/10 hover:bg-white/20 text-white',
  },
  {
    id: 'purple',
    name: 'Royal Amethyst',
    description: 'Vibrant purple and fuchsia cosmic gradient',
    previewColor: '#3b0764',
    previewGradient: 'from-purple-950 via-fuchsia-950 to-indigo-950',
    pageBg: 'bg-gradient-to-b from-purple-950 via-fuchsia-950 to-indigo-950',
    headerBg: '#3b0764',
    headerOverlay: 'bg-gradient-to-b from-black/20 via-transparent to-purple-950/90',
    cardBg: 'bg-white/10 hover:bg-white/20',
    cardBorder: 'border border-purple-500/20',
    textColor: 'text-white',
    headingColor: 'text-white',
    mutedTextColor: 'text-purple-200/80',
    subtitleColor: 'text-purple-200/70',
    iconBg: 'bg-gradient-to-br from-purple-500/50 to-fuchsia-600/50',
    buttonStyle: 'bg-white/10 hover:bg-white/20 text-white',
  },
  {
    id: 'minimal-light',
    name: 'Clean Ivory',
    description: 'Crisp light theme with subtle slate cards',
    previewColor: '#f1f5f9',
    previewGradient: 'from-slate-100 to-slate-200',
    pageBg: 'bg-gradient-to-b from-slate-100 to-slate-200',
    headerBg: '#e2e8f0',
    headerOverlay: 'bg-gradient-to-b from-transparent via-transparent to-slate-100/90',
    cardBg: 'bg-white hover:bg-slate-50 shadow-md',
    cardBorder: 'border border-slate-200/80',
    textColor: 'text-slate-900',
    headingColor: 'text-slate-900',
    mutedTextColor: 'text-slate-600',
    subtitleColor: 'text-slate-500',
    iconBg: 'bg-gradient-to-br from-blue-100 to-indigo-100 text-blue-600',
    buttonStyle: 'bg-slate-200/80 hover:bg-slate-300 text-slate-800',
  },
  {
    id: 'cyberpunk',
    name: 'Neon Cyber',
    description: 'High-contrast dark terminal with electric yellow accents',
    previewColor: '#000000',
    previewGradient: 'from-black via-zinc-950 to-black',
    pageBg: 'bg-gradient-to-b from-black via-zinc-950 to-black',
    headerBg: '#09090b',
    headerOverlay: 'bg-gradient-to-b from-black/40 via-transparent to-black/90',
    cardBg: 'bg-zinc-900/80 hover:bg-zinc-800/90',
    cardBorder: 'border border-yellow-400/40 shadow-[0_0_15px_rgba(250,204,21,0.15)]',
    textColor: 'text-yellow-300',
    headingColor: 'text-yellow-300',
    mutedTextColor: 'text-yellow-200/70',
    subtitleColor: 'text-yellow-100/60',
    iconBg: 'bg-yellow-400/20 text-yellow-300 ring-1 ring-yellow-400/50',
    buttonStyle: 'bg-zinc-900 border border-yellow-400/30 text-yellow-300 hover:bg-zinc-800',
  },
  {
    id: 'crimson',
    name: 'Crimson Noir',
    description: 'Deep ruby red fading into velvet black',
    previewColor: '#450a0a',
    previewGradient: 'from-red-950 via-zinc-950 to-black',
    pageBg: 'bg-gradient-to-b from-red-950 via-zinc-950 to-black',
    headerBg: '#450a0a',
    headerOverlay: 'bg-gradient-to-b from-black/30 via-transparent to-black/90',
    cardBg: 'bg-white/10 hover:bg-white/20',
    cardBorder: 'border border-red-500/20',
    textColor: 'text-white',
    headingColor: 'text-white',
    mutedTextColor: 'text-red-200/80',
    subtitleColor: 'text-red-200/70',
    iconBg: 'bg-gradient-to-br from-red-500/50 to-rose-600/50',
    buttonStyle: 'bg-white/10 hover:bg-white/20 text-white',
  },
];

/**
 * Retrieves a theme preset by its ID key, falling back safely to the default theme.
 *
 * @param {string | null | undefined} key
 * @returns {typeof themes[0]}
 */
export function getTheme(key) {
  if (!key) return themes[0];
  const found = themes.find((t) => t.id === key);
  return found || themes[0];
}
